// Generated by `npx e9core build-plugins`. Do not edit.
// Packages: @engine9/interfaces
// Regenerate after changing plugin dependencies or "engine9" in package.json.
export default {
  "@engine9/interfaces/channels/email": {
    index: () => import("@engine9/interfaces/channels/email/index.js")
  },
  "@engine9/interfaces/event": {
    index: () => import("@engine9/interfaces/event/index.js"),
    schema: () => import("@engine9/interfaces/event/schema.js")
  },
  "@engine9/interfaces/message": {
    index: () => import("@engine9/interfaces/message/index.js"),
    schema: () => import("@engine9/interfaces/message/schema.js"),
    console: {
      "menu": {
        "message-menu": {
          "title": "Messages",
          "icon": "messages",
          "type": "collapse",
          "children": {
            "campaigns": {
              "title": "Campaigns",
              "icon": "campaign",
              "url": "/campaign"
            }
          }
        }
      },
      "routes": {
        "campaign": {
          "layout": "full_width",
          "components": {
            "header": [
              "Campaigns",
              {
                "component": "Button",
                "properties": {
                  "icon": "plus",
                  "content": "Add Campaign",
                  "onClick": {
                    "action": "navigate",
                    "url": "/campaign/create"
                  }
                }
              }
            ],
            "main": [
              {
                "component": "RecordTable",
                "properties": {
                  "table": "campaign",
                  "columns": [
                    {
                      "title": "Id",
                      "dataIndex": "id",
                      "sorter": true,
                      "width": "20%"
                    },
                    {
                      "title": "Name",
                      "dataIndex": "name",
                      "sorter": true,
                      "template": "{{name}}",
                      "width": "40%"
                    }
                  ],
                  "onRecord": {
                    "onClick": {
                      "action": "navigate",
                      "url": "/campaign/{{record.id}}"
                    }
                  }
                }
              }
            ]
          }
        },
        "campaign/create": {
          "layout": "full_width",
          "components": {
            "main": [
              {
                "path": "edit",
                "component": "RecordForm",
                "properties": {
                  "table": "campaign",
                  "form": {
                    "title": "Create Campaign",
                    "type": "object",
                    "required": [],
                    "properties": {
                      "name": {
                        "type": "string",
                        "title": "Name",
                        "default": ""
                      }
                    }
                  },
                  "uiSchema": {},
                  "onSave": {
                    "action": "navigate",
                    "url": "/campaign/{{record.id}}"
                  }
                }
              }
            ]
          }
        },
        "campaign/:id/*": {
          "layout": "sidebar",
          "components": {
            "sidebar": {
              "items": [
                {
                  "component": "Title",
                  "properties": {
                    "content": "Emails"
                  }
                },
                {
                  "component": "Button",
                  "properties": {
                    "icon": "plus",
                    "content": "Add Message Set",
                    "onClick": {
                      "action": "object.create",
                      "data": {
                        "type": "message_set",
                        "attributes": {
                          "label": "Messages - {{date \"MMMM, yyyy\"}}",
                          "campaign_id": "{{parameters.id}}"
                        }
                      },
                      "redirect": "/campaign/{{parameters.id}}/message_set/{{record.id}}"
                    }
                  }
                },
                {
                  "component": "RecordList",
                  "properties": {
                    "table": "message_set",
                    "conditions": [
                      {
                        "eql": "campaign_id={{id}}"
                      }
                    ],
                    "onRecord": {
                      "onClick": {
                        "action": "navigate",
                        "url": "/campaign/{{parameters.id}}/message_set/{{record.id}}/"
                      }
                    }
                  }
                }
              ]
            },
            "main": [
              {
                "component": "Title",
                "properties": {
                  "content": "Campaign Summary"
                }
              },
              {
                "component": "RecordDisplay",
                "properties": {
                  "table": "campaign",
                  "id": "{{parameters.id}}",
                  "template": "{{name}}"
                }
              }
            ]
          }
        },
        "message": {
          "layout": "full_width",
          "components": {
            "main": [
              {
                "component": "RecordTable",
                "properties": {
                  "table": "message",
                  "columns": [
                    {
                      "title": "Id",
                      "dataIndex": "id",
                      "sorter": true,
                      "width": "20%"
                    },
                    {
                      "title": "Publish Date",
                      "dataIndex": "publish_date",
                      "sorter": true,
                      "width": "40%"
                    },
                    {
                      "title": "Name",
                      "dataIndex": "name",
                      "sorter": true,
                      "template": "{{name}}",
                      "width": "40%"
                    }
                  ],
                  "onRecord": {
                    "onClick": {
                      "action": "navigate",
                      "url": "/message/{{record.id}}"
                    }
                  }
                }
              }
            ]
          }
        },
        "message/:id/*": {
          "layout": "sidebar",
          "components": {
            "sidebar": [
              {
                "component": "RecordDisplay",
                "properties": {
                  "table": "message",
                  "id": "{{parameters.id}}",
                  "components": [
                    "{{name}}"
                  ]
                }
              }
            ],
            "main": [
              {
                "component": "RecordDisplay",
                "properties": {
                  "table": "message",
                  "id": "{{parameters.id}}",
                  "components": [
                    "{{name}}"
                  ]
                }
              },
              {
                "path": "source_codes",
                "label": "Source Codes",
                "component": "RecordDisplay",
                "properties": {
                  "table": "message",
                  "id": "{{parameters.id}}",
                  "includes": {
                    "source_codes": {
                      "table": "source_code"
                    }
                  },
                  "components": [
                    "{{source_code}}"
                  ]
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/person": {
    index: () => import("@engine9/interfaces/person/index.js"),
    schema: () => import("@engine9/interfaces/person/schema.js"),
    console: {
      "menu": {
        "people": {
          "title": "People",
          "icon": "people",
          "type": "collapse",
          "children": {
            "person-list": {
              "title": "Everybody",
              "icon": "person",
              "url": "/person"
            }
          }
        }
      },
      "routes": {
        "person": {
          "layout": "full_width",
          "components": {
            "header": [
              "Everybody",
              {
                "component": "Button",
                "properties": {
                  "icon": "plus",
                  "content": "Add Person",
                  "onClick": {
                    "action": "navigate",
                    "url": "/person/create"
                  }
                }
              }
            ],
            "main": [
              {
                "component": "RecordList",
                "properties": {
                  "table": "person",
                  "includes": {
                    "emails": {
                      "table": "person_email"
                    }
                  },
                  "columns": [
                    {
                      "title": "Id",
                      "dataIndex": "id",
                      "sorter": true,
                      "width": "20%"
                    },
                    {
                      "title": "Name",
                      "dataIndex": "name",
                      "sorter": true,
                      "template": "{{given_name}} {{family_name}} {{emails.0.email}}",
                      "width": "40%"
                    },
                    {
                      "title": "Email",
                      "template": "{{emails.0.email}}",
                      "width": "40%"
                    }
                  ],
                  "onRow": {
                    "onClick": {
                      "action": "navigate",
                      "url": "/person/{{record.id}}"
                    }
                  }
                }
              }
            ]
          }
        },
        "person/create": {
          "layout": "full_width",
          "components": {
            "main": [
              {
                "path": "edit",
                "component": "RecordForm",
                "properties": {
                  "table": "person",
                  "form": {
                    "title": "Todo",
                    "type": "object",
                    "required": [],
                    "properties": {
                      "given_name": {
                        "type": "string",
                        "title": "First Name",
                        "default": ""
                      },
                      "family_name": {
                        "type": "string",
                        "title": "Last Name",
                        "default": ""
                      }
                    }
                  },
                  "uiSchema": {
                    "family_name": {
                      "ui:widget": "textarea"
                    }
                  },
                  "onSave": {
                    "action": "navigate",
                    "url": "/person/{{record.id}}"
                  }
                }
              }
            ]
          }
        },
        "person/:id/*": {
          "layout": "sidebar",
          "components": {
            "sidebar": {
              "title": "Person Details",
              "items": [
                {
                  "component": "RecordDisplay",
                  "properties": {
                    "table": "person",
                    "id": "{{parameters.id}}",
                    "includes": {
                      "emails": {
                        "table": "person_email",
                        "orderBy": "preference_order"
                      }
                    },
                    "template": "{{given_name}} {{family_name}} {{#if emails.0.email}}<{{emails.0.email}}>{{/if}}"
                  }
                },
                {
                  "component": "Link",
                  "properties": {
                    "label": "Edit",
                    "to": "edit"
                  }
                }
              ]
            },
            "main": [
              {
                "component": "RecordDisplay",
                "properties": {
                  "table": "person",
                  "id": "{{parameters.id}}",
                  "template": "{{given_name}} {{family_name}}"
                }
              },
              {
                "path": "edit",
                "component": "RecordForm",
                "properties": {
                  "table": "person",
                  "id": "{{parameters.id}}",
                  "form": {
                    "title": "Todo",
                    "type": "object",
                    "required": [],
                    "properties": {
                      "given_name": {
                        "type": "string",
                        "title": "First Name",
                        "default": ""
                      },
                      "family_name": {
                        "type": "string",
                        "title": "Last Name",
                        "default": ""
                      }
                    }
                  }
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/person_address": {
    index: () => import("@engine9/interfaces/person_address/index.js"),
    schema: () => import("@engine9/interfaces/person_address/schema.js"),
    console: {
      "routes": {
        "person/:id/*": {
          "components": {
            "sidebar": {
              "items": [
                {
                  "component": "Link",
                  "properties": {
                    "label": "Addresses",
                    "to": "address"
                  }
                }
              ]
            },
            "main": [
              {
                "path": "address",
                "label": "Addresses",
                "component": "RecordDisplay",
                "properties": {
                  "table": "person_address",
                  "conditions": [
                    {
                      "eql": "person_id={{person_id}}"
                    }
                  ],
                  "rows": [
                    "{{street}}"
                  ]
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/person_custom": {
    index: () => import("@engine9/interfaces/person_custom/index.js")
  },
  "@engine9/interfaces/person_email": {
    index: () => import("@engine9/interfaces/person_email/index.js"),
    schema: () => import("@engine9/interfaces/person_email/schema.js"),
    console: {
      "routes": {
        "person/:id/*": {
          "components": {
            "sidebar": {
              "items": [
                {
                  "component": "Link",
                  "properties": {
                    "label": "Emails",
                    "to": "emails"
                  }
                }
              ]
            },
            "main": [
              {
                "path": "emails",
                "label": "Emails",
                "component": "RecordTable",
                "properties": {
                  "table": "person_email",
                  "conditions": [
                    {
                      "eql": "person_id={{id}}"
                    }
                  ],
                  "columns": [
                    {
                      "title": "Id",
                      "dataIndex": "id",
                      "sorter": true,
                      "width": "20%"
                    },
                    {
                      "title": "Email",
                      "template": "{{email}}",
                      "width": "40%"
                    },
                    {
                      "title": "Type",
                      "template": "{{email_type}}",
                      "width": "10%"
                    },
                    {
                      "title": "Subscription Status",
                      "template": "{{subscription_status}}",
                      "width": "15%"
                    },
                    {
                      "title": "Modified",
                      "template": "{{date modified_at}}",
                      "width": "15%"
                    }
                  ]
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/person_hash": {
    index: () => import("@engine9/interfaces/person_hash/index.js"),
    schema: () => import("@engine9/interfaces/person_hash/schema.js"),
    console: {
      "routes": {
        "person/:id/*": {
          "components": {
            "sidebar": {
              "items": [
                {
                  "component": "Link",
                  "properties": {
                    "label": "Email hashes",
                    "to": "email_hashes"
                  }
                },
                {
                  "component": "Link",
                  "properties": {
                    "label": "Phone hashes",
                    "to": "phone_hashes"
                  }
                }
              ]
            },
            "main": [
              {
                "path": "email_hashes",
                "label": "Email hashes",
                "component": "RecordTable",
                "properties": {
                  "table": "person_hash_email",
                  "conditions": [
                    {
                      "eql": "person_id={{id}}"
                    }
                  ],
                  "columns": [
                    {
                      "title": "SHA-256",
                      "template": "{{email_hash_v1}}",
                      "width": "45%"
                    },
                    {
                      "title": "MD5",
                      "template": "{{email_hash_md5}}",
                      "width": "35%"
                    },
                    {
                      "title": "Modified",
                      "template": "{{date modified_at}}",
                      "width": "20%"
                    }
                  ]
                }
              },
              {
                "path": "phone_hashes",
                "label": "Phone hashes",
                "component": "RecordTable",
                "properties": {
                  "table": "person_hash_phone",
                  "conditions": [
                    {
                      "eql": "person_id={{id}}"
                    }
                  ],
                  "columns": [
                    {
                      "title": "SHA-256",
                      "template": "{{phone_hash_v1}}",
                      "width": "45%"
                    },
                    {
                      "title": "MD5",
                      "template": "{{phone_hash_md5}}",
                      "width": "35%"
                    },
                    {
                      "title": "Modified",
                      "template": "{{date modified_at}}",
                      "width": "20%"
                    }
                  ]
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/person_phone": {
    index: () => import("@engine9/interfaces/person_phone/index.js"),
    schema: () => import("@engine9/interfaces/person_phone/schema.js"),
    console: {
      "routes": {
        "person/:id/*": {
          "components": {
            "sidebar": {
              "items2": [
                {
                  "component": "Link",
                  "properties": {
                    "label": "Phones",
                    "to": "phones"
                  }
                }
              ]
            },
            "main": [
              {
                "path": "phones",
                "label": "Phones",
                "component": "RecordDisplay",
                "properties": {
                  "table": "person_phone",
                  "conditions": [
                    {
                      "eql": "person_id={{person_id}}"
                    }
                  ],
                  "rows": [
                    "{{phone}}",
                    "{{phone_type}}"
                  ]
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/person_remote": {
    index: () => import("@engine9/interfaces/person_remote/index.js"),
    schema: () => import("@engine9/interfaces/person_remote/schema.js")
  },
  "@engine9/interfaces/plugin": {
    index: () => import("@engine9/interfaces/plugin/index.js"),
    schema: () => import("@engine9/interfaces/plugin/schema.js"),
    settings: () => import("@engine9/interfaces/plugin/settings.js"),
    console: {
      "menu": {
        "settings": {
          "children": {
            "queries": {
              "title": "Plugins",
              "icon": "plugins",
              "url": "/plugins"
            }
          }
        }
      },
      "routes": {
        "plugins": {
          "layout": "full_width",
          "components": {
            "header": [
              "Plugins"
            ],
            "main": [
              {
                "component": "RecordTable",
                "properties": {
                  "table": "plugin",
                  "columns": [
                    {
                      "title": "Id",
                      "dataIndex": "id",
                      "sorter": true,
                      "width": "20%"
                    },
                    {
                      "title": "Name",
                      "dataIndex": "name",
                      "sorter": true,
                      "template": "{{name}}",
                      "width": "40%"
                    }
                  ],
                  "onRecord": {
                    "onClick": {
                      "action": "navigate",
                      "url": "/plugins/{{record.id}}"
                    }
                  }
                }
              }
            ]
          }
        },
        "plugins/:id/*": {
          "layout": "full_width",
          "components": {
            "main": [
              {
                "component": "RecordForm",
                "properties": {
                  "table": "job",
                  "title": "{{#if record.id}}Edit Plugin{{else}}Create Job{{/if}}",
                  "form": {
                    "type": "object",
                    "required": [],
                    "properties": {
                      "status": {
                        "type": "string",
                        "title": "Status",
                        "default": "pending"
                      },
                      "options": {
                        "type": "string",
                        "title": "Options",
                        "default": "{}"
                      }
                    }
                  },
                  "uiSchema": {
                    "options": {
                      "ui:widget": "textarea"
                    }
                  },
                  "onSave": {
                    "action": "navigate",
                    "url": "/plugins/{{record.id}}"
                  }
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/report": {
    index: () => import("@engine9/interfaces/report/index.js"),
    console: {
      "menu": {
        "data-menu": {
          "children": {
            "report": {
              "title": "Reports",
              "icon": "report",
              "url": "/report"
            }
          }
        }
      },
      "routes": {
        "/report": {
          "layout": "full_width",
          "components": {
            "main": [
              "<h1>Reports</h1>"
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/segment": {
    index: () => import("@engine9/interfaces/segment/index.js"),
    schema: () => import("@engine9/interfaces/segment/schema.js"),
    console: {
      "menu": {
        "people": {
          "children": {
            "segments": {
              "title": "Segments",
              "icon": "people",
              "url": "/segments"
            }
          }
        }
      },
      "routes": {
        "/segments": {
          "layout": "full_width",
          "components": {
            "header": [
              "Segments",
              {
                "component": "Button",
                "properties": {
                  "icon": "plus",
                  "content": "Add Segment",
                  "onClick": {
                    "action": "navigate",
                    "url": "/segments/create"
                  }
                }
              }
            ],
            "main": [
              {
                "component": "RecordTable",
                "properties": {
                  "table": "segment",
                  "columns": [
                    {
                      "title": "Id",
                      "dataIndex": "id",
                      "sorter": true,
                      "width": "20%"
                    },
                    {
                      "title": "Type",
                      "dataIndex": "type",
                      "sorter": true
                    },
                    {
                      "title": "Name",
                      "dataIndex": "label",
                      "sorter": true,
                      "template": "{{label}}",
                      "width": "40%"
                    }
                  ],
                  "onRecord": {
                    "onClick": {
                      "action": "navigate",
                      "url": "/segments/{{record.id}}"
                    }
                  }
                }
              }
            ]
          }
        },
        "/segments/:id/*": {
          "layout": "full_width",
          "components": {
            "main": [
              {
                "component": "RecordForm",
                "properties": {
                  "table": "job",
                  "title": "{{#if record.id}}Edit Segment{{else}}Create Segment{{/if}}",
                  "form": {
                    "type": "object",
                    "required": [],
                    "properties": {
                      "type": {
                        "type": "string",
                        "title": "Type"
                      },
                      "name": {
                        "type": "string",
                        "title": "Name"
                      },
                      "plugin_id": {
                        "type": "string",
                        "title": "Source Plugin ID"
                      },
                      "remote_segment_id": {
                        "type": "string",
                        "title": "Remote Segment ID"
                      },
                      "build_mechanism": {
                        "type": "string",
                        "title": "Mechanism",
                        "default": "static"
                      },
                      "build_schedule": {
                        "type": "string",
                        "title": "Build Schedule"
                      },
                      "build_status": {
                        "type": "string",
                        "title": "Build Status"
                      },
                      "build_status_modified_at": {
                        "type": "modified_at",
                        "title": "Build Status Modified At"
                      }
                    }
                  },
                  "uiSchema": {},
                  "onSave": {
                    "action": "navigate",
                    "url": "/segments/{{record.id}}"
                  }
                }
              },
              {
                "component": "RecordTable",
                "properties": {
                  "table": "person_segment",
                  "includes": [
                    {
                      "alias": "people",
                      "table": "person"
                    }
                  ],
                  "conditions": [
                    {
                      "eql": "segment_id={{parameters.segment_id}}"
                    }
                  ],
                  "columns": [
                    {
                      "template": "{{person_id}}"
                    }
                  ]
                }
              }
            ]
          }
        },
        "/person/:id/*": {
          "components": {
            "sidebar": {
              "items2": [
                {
                  "component": "Link",
                  "properties": {
                    "label": "Segments",
                    "to": "segments"
                  }
                }
              ]
            },
            "main": [
              {
                "path": "segments",
                "label": "Segments",
                "component": "RecordTable",
                "properties": {
                  "table": "person_segment",
                  "includes": [
                    {
                      "alias": "segments",
                      "table": "segment"
                    }
                  ],
                  "conditions": [
                    {
                      "eql": "person_id={{parameters.person_id}}"
                    }
                  ],
                  "rows": [
                    "{{segment}}"
                  ]
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/segment_stats": {
    index: () => import("@engine9/interfaces/segment_stats/index.js"),
    schema: () => import("@engine9/interfaces/segment_stats/schema.js")
  },
  "@engine9/interfaces/source_code": {
    index: () => import("@engine9/interfaces/source_code/index.js"),
    schema: () => import("@engine9/interfaces/source_code/schema.js"),
    console: {
      "routes": {
        "/person/:id/*": {
          "components": {
            "sidebar": {
              "items": [
                {
                  "component": "Link",
                  "properties": {
                    "label": "Timeline",
                    "to": "timeline"
                  }
                }
              ]
            },
            "main": [
              {
                "path": "timeline",
                "label": "Timeline",
                "component": "RecordDisplay",
                "properties": {
                  "table": "timeline",
                  "conditions": [
                    {
                      "eql": "person_id={{person_id}}"
                    }
                  ],
                  "rows": [
                    "{{email}}"
                  ]
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/stacks/limited-pii": {
    index: () => import("@engine9/interfaces/stacks/limited-pii/index.js")
  },
  "@engine9/interfaces/stacks/standard": {
    index: () => import("@engine9/interfaces/stacks/standard/index.js")
  },
  "@engine9/interfaces/tag": {
    index: () => import("@engine9/interfaces/tag/index.js"),
    schema: () => import("@engine9/interfaces/tag/schema.js")
  },
  "@engine9/interfaces/task": {
    index: () => import("@engine9/interfaces/task/index.js"),
    schema: () => import("@engine9/interfaces/task/schema.js"),
    console: {
      "menu": {
        "data-menu": {
          "title": "Data",
          "icon": "data",
          "type": "collapse",
          "children": {
            "task": {
              "title": "Tasks",
              "icon": "forklift",
              "url": "/task"
            }
          }
        }
      },
      "routes": {
        "task": {
          "layout": "full_width",
          "components": {
            "header": [
              "Tasks"
            ],
            "main": [
              {
                "component": "RecordTable",
                "properties": {
                  "table": "task_run",
                  "columns": [
                    {
                      "title": "Id",
                      "dataIndex": "id",
                      "sorter": true,
                      "width": "24%"
                    },
                    {
                      "title": "Created",
                      "dataIndex": "created_at",
                      "sorter": true,
                      "width": "18%"
                    },
                    {
                      "title": "State",
                      "dataIndex": "state_type",
                      "sorter": true,
                      "width": "14%"
                    },
                    {
                      "title": "Task Key",
                      "dataIndex": "task_key",
                      "sorter": true,
                      "width": "22%"
                    },
                    {
                      "title": "Flow Run",
                      "dataIndex": "flow_run_id",
                      "sorter": true,
                      "width": "22%"
                    }
                  ],
                  "onRecord": {
                    "onClick": {
                      "action": "navigate",
                      "url": "/task/{{record.id}}"
                    }
                  }
                }
              }
            ]
          }
        },
        "task/:id/*": {
          "layout": "full_width",
          "components": {
            "main": [
              {
                "component": "RecordForm",
                "properties": {
                  "table": "task_run",
                  "title": "Task Run {{record.id}}",
                  "readOnly": true
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/timeline": {
    index: () => import("@engine9/interfaces/timeline/index.js"),
    schema: () => import("@engine9/interfaces/timeline/schema.js"),
    console: {
      "routes": {
        "/person/:id/*": {
          "components": {
            "sidebar": {
              "items": [
                {
                  "component": "Link",
                  "properties": {
                    "label": "Timeline",
                    "to": "timeline"
                  }
                }
              ]
            },
            "main": [
              {
                "path": "timeline",
                "label": "Timeline",
                "component": "RecordDisplay",
                "properties": {
                  "table": "timeline",
                  "conditions": [
                    {
                      "eql": "person_id={{person_id}}"
                    }
                  ],
                  "rows": [
                    "{{email}}"
                  ]
                }
              }
            ]
          }
        }
      }
    }
  },
  "@engine9/interfaces/transaction/contact_details": {
    index: () => import("@engine9/interfaces/transaction/contact_details/index.js"),
    schema: () => import("@engine9/interfaces/transaction/contact_details/schema.js")
  },
  "@engine9/interfaces/transaction/core": {
    index: () => import("@engine9/interfaces/transaction/core/index.js"),
    schema: () => import("@engine9/interfaces/transaction/core/schema.js")
  }
};
